# ~/public/admin/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: lazgps/sv-gps
publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}:{{minute}}_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - {label: "Topic", name: "topic", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["Property Management"]}
      - {label: "Body", name: "body", widget: "markdown"}

editor:
  preview: true
  sumary: "{{commit_date}}-{{title}}}"
